(()=>{
'use strict';
const select=document.getElementById('languageSelect');if(!select)return;
const exact={
fr:{'Projects':'Projets','Save current':'Enregistrer','No active project':'Aucun projet actif','2D Plan':'Plan 2D','3D Visualisation':'Visualisation 3D','Harness Reference':'Référence harnais','Language':'Langue','Tutorial':'Tutoriel','Build This':'Construire ceci','Build':'Construire','Units':'Unités','Scale':'Échelle','Measure 2D':'Mesurer en 2D','Live Rope: Off':'Corde active : désactivée','Live Rope: On':'Corde active : activée','3D Measurements':'Mesures 3D','Set point A':'Définir le point A','Set point B':'Définir le point B','Clear':'Effacer'},
es:{'Projects':'Proyectos','Save current':'Guardar actual','No active project':'Sin proyecto activo','2D Plan':'Plano 2D','3D Visualisation':'Visualización 3D','Harness Reference':'Referencia de arnés','Language':'Idioma','Tutorial':'Tutorial','Build This':'Construir esto','Build':'Construir','Units':'Unidades','Scale':'Escala','Measure 2D':'Medir 2D','Live Rope: Off':'Cuerda activa: desactivada','Live Rope: On':'Cuerda activa: activada','3D Measurements':'Mediciones 3D','Set point A':'Definir punto A','Set point B':'Definir punto B','Clear':'Borrar'},
de:{'Projects':'Projekte','Save current':'Aktuelles speichern','No active project':'Kein aktives Projekt','2D Plan':'2D-Plan','3D Visualisation':'3D-Visualisierung','Harness Reference':'Gurtzeug-Referenz','Language':'Sprache','Tutorial':'Anleitung','Build This':'Dies bauen','Build':'Bauen','Units':'Einheiten','Scale':'Maßstab','Measure 2D':'2D messen','Live Rope: Off':'Live-Seil: Aus','Live Rope: On':'Live-Seil: Ein','3D Measurements':'3D-Messungen','Set point A':'Punkt A setzen','Set point B':'Punkt B setzen','Clear':'Löschen'},
zh:{'Projects':'项目','Save current':'保存当前','No active project':'无活动项目','2D Plan':'二维计划','3D Visualisation':'三维可视化','Harness Reference':'安全带参考','Language':'语言','Tutorial':'教程','Build This':'按描述构建','Build':'构建','Units':'单位','Scale':'比例','Measure 2D':'二维测量','Live Rope: Off':'实时绳索：关闭','Live Rope: On':'实时绳索：开启','3D Measurements':'三维测量','Set point A':'设置 A 点','Set point B':'设置 B 点','Clear':'清除'},
ja:{'Projects':'プロジェクト','Save current':'現在を保存','No active project':'アクティブなプロジェクトなし','2D Plan':'2Dプラン','3D Visualisation':'3D表示','Harness Reference':'ハーネス参照','Language':'言語','Tutorial':'チュートリアル','Build This':'指示から構築','Build':'構築','Units':'単位','Scale':'縮尺','Measure 2D':'2D測定','Live Rope: Off':'ライブロープ：オフ','Live Rope: On':'ライブロープ：オン','3D Measurements':'3D測定','Set point A':'点Aを設定','Set point B':'点Bを設定','Clear':'クリア'},
th:{'Projects':'โครงการ','Save current':'บันทึกปัจจุบัน','No active project':'ไม่มีโครงการที่ใช้งาน','2D Plan':'แผน 2D','3D Visualisation':'มุมมอง 3D','Harness Reference':'ข้อมูลอ้างอิงฮาร์เนส','Language':'ภาษา','Tutorial':'บทแนะนำ','Build This':'สร้างตามคำสั่ง','Build':'สร้าง','Units':'หน่วย','Scale':'มาตราส่วน','Measure 2D':'วัด 2D','Live Rope: Off':'เชือกสด: ปิด','Live Rope: On':'เชือกสด: เปิด','3D Measurements':'การวัด 3D','Set point A':'ตั้งจุด A','Set point B':'ตั้งจุด B','Clear':'ล้าง'}
};
const words={
fr:{Select:'Sélectionner',Line:'Ligne',Arrow:'Flèche',Text:'Texte',Add:'Ajouter',Delete:'Supprimer',Duplicate:'Dupliquer',Undo:'Annuler',Redo:'Rétablir',Download:'Télécharger',Image:'image',PDF:'PDF',Background:'Arrière-plan',Upload:'Importer',Remove:'Retirer',Opacity:'Opacité',Equipment:'Équipement',Search:'Rechercher',Name:'Nom',Location:'Lieu',Date:'Date',Load:'Charge',Weight:'Poids',Ratio:'Rapport',Force:'Force',Height:'Hauteur',Length:'Longueur',Distance:'Distance',Position:'Position',Rotation:'Rotation',Timeline:'Chronologie',Calendar:'Calendrier',Today:"Aujourd'hui",Create:'Créer',Project:'Projet',Workspace:'Espace de travail',Settings:'Réglages',Close:'Fermer',Save:'Enregistrer',Open:'Ouvrir',Current:'Actuel',Selected:'Sélectionné',Object:'Objet',Rope:'Corde',Pulley:'Poulie',Performer:'Interprète',Anchor:'Ancrage',Warning:'Avertissement',Ready:'Prêt',None:'Aucun',Ground:'Sol'},
es:{Select:'Seleccionar',Line:'Línea',Arrow:'Flecha',Text:'Texto',Add:'Añadir',Delete:'Eliminar',Duplicate:'Duplicar',Undo:'Deshacer',Redo:'Rehacer',Download:'Descargar',Image:'imagen',Background:'Fondo',Upload:'Subir',Remove:'Quitar',Opacity:'Opacidad',Equipment:'Equipo',Search:'Buscar',Name:'Nombre',Location:'Ubicación',Date:'Fecha',Load:'Carga',Weight:'Peso',Ratio:'Relación',Force:'Fuerza',Height:'Altura',Length:'Longitud',Distance:'Distancia',Position:'Posición',Rotation:'Rotación',Timeline:'Cronología',Calendar:'Calendario',Today:'Hoy',Create:'Crear',Project:'Proyecto',Workspace:'Espacio de trabajo',Settings:'Ajustes',Close:'Cerrar',Save:'Guardar',Open:'Abrir',Current:'Actual',Selected:'Seleccionado',Object:'Objeto',Rope:'Cuerda',Pulley:'Polea',Performer:'Artista',Anchor:'Anclaje',Warning:'Advertencia',Ready:'Listo',None:'Ninguno',Ground:'Suelo'},
de:{Select:'Auswählen',Line:'Linie',Arrow:'Pfeil',Text:'Text',Add:'Hinzufügen',Delete:'Löschen',Duplicate:'Duplizieren',Undo:'Rückgängig',Redo:'Wiederholen',Download:'Herunterladen',Image:'Bild',Background:'Hintergrund',Upload:'Hochladen',Remove:'Entfernen',Opacity:'Deckkraft',Equipment:'Ausrüstung',Search:'Suchen',Name:'Name',Location:'Ort',Date:'Datum',Load:'Last',Weight:'Gewicht',Ratio:'Verhältnis',Force:'Kraft',Height:'Höhe',Length:'Länge',Distance:'Entfernung',Position:'Position',Rotation:'Drehung',Timeline:'Zeitleiste',Calendar:'Kalender',Today:'Heute',Create:'Erstellen',Project:'Projekt',Workspace:'Arbeitsbereich',Settings:'Einstellungen',Close:'Schließen',Save:'Speichern',Open:'Öffnen',Current:'Aktuell',Selected:'Ausgewählt',Object:'Objekt',Rope:'Seil',Pulley:'Rolle',Performer:'Darsteller',Anchor:'Anker',Warning:'Warnung',Ready:'Bereit',None:'Keine',Ground:'Boden'},
zh:{Select:'选择',Line:'线',Arrow:'箭头',Text:'文本',Add:'添加',Delete:'删除',Duplicate:'复制',Undo:'撤销',Redo:'重做',Download:'下载',Image:'图像',Background:'背景',Upload:'上传',Remove:'移除',Opacity:'透明度',Equipment:'设备',Search:'搜索',Name:'名称',Location:'位置',Date:'日期',Load:'负载',Weight:'重量',Ratio:'倍率',Force:'力',Height:'高度',Length:'长度',Distance:'距离',Position:'位置',Rotation:'旋转',Timeline:'时间线',Calendar:'日历',Today:'今天',Create:'创建',Project:'项目',Workspace:'工作区',Settings:'设置',Close:'关闭',Save:'保存',Open:'打开',Current:'当前',Selected:'已选择',Object:'对象',Rope:'绳索',Pulley:'滑轮',Performer:'表演者',Anchor:'锚点',Warning:'警告',Ready:'就绪',None:'无',Ground:'地面'},
ja:{Select:'選択',Line:'線',Arrow:'矢印',Text:'テキスト',Add:'追加',Delete:'削除',Duplicate:'複製',Undo:'元に戻す',Redo:'やり直す',Download:'ダウンロード',Image:'画像',Background:'背景',Upload:'アップロード',Remove:'削除',Opacity:'不透明度',Equipment:'機材',Search:'検索',Name:'名前',Location:'場所',Date:'日付',Load:'荷重',Weight:'重量',Ratio:'比率',Force:'力',Height:'高さ',Length:'長さ',Distance:'距離',Position:'位置',Rotation:'回転',Timeline:'タイムライン',Calendar:'カレンダー',Today:'今日',Create:'作成',Project:'プロジェクト',Workspace:'作業領域',Settings:'設定',Close:'閉じる',Save:'保存',Open:'開く',Current:'現在',Selected:'選択済み',Object:'オブジェクト',Rope:'ロープ',Pulley:'プーリー',Performer:'パフォーマー',Anchor:'アンカー',Warning:'警告',Ready:'準備完了',None:'なし',Ground:'地面'},
th:{Select:'เลือก',Line:'เส้น',Arrow:'ลูกศร',Text:'ข้อความ',Add:'เพิ่ม',Delete:'ลบ',Duplicate:'ทำซ้ำ',Undo:'ย้อนกลับ',Redo:'ทำซ้ำอีกครั้ง',Download:'ดาวน์โหลด',Image:'รูปภาพ',Background:'พื้นหลัง',Upload:'อัปโหลด',Remove:'นำออก',Opacity:'ความทึบ',Equipment:'อุปกรณ์',Search:'ค้นหา',Name:'ชื่อ',Location:'สถานที่',Date:'วันที่',Load:'โหลด',Weight:'น้ำหนัก',Ratio:'อัตราส่วน',Force:'แรง',Height:'ความสูง',Length:'ความยาว',Distance:'ระยะทาง',Position:'ตำแหน่ง',Rotation:'การหมุน',Timeline:'ไทม์ไลน์',Calendar:'ปฏิทิน',Today:'วันนี้',Create:'สร้าง',Project:'โครงการ',Workspace:'พื้นที่ทำงาน',Settings:'การตั้งค่า',Close:'ปิด',Save:'บันทึก',Open:'เปิด',Current:'ปัจจุบัน',Selected:'เลือกแล้ว',Object:'วัตถุ',Rope:'เชือก',Pulley:'รอก',Performer:'ผู้แสดง',Anchor:'จุดยึด',Warning:'คำเตือน',Ready:'พร้อม',None:'ไม่มี',Ground:'พื้น'}
};
const originals=new WeakMap(),attrs=new WeakMap();let lang='en',busy=false;
function translate(str){if(lang==='en')return str;const trimmed=str.trim();if(!trimmed)return str;const ex=exact[lang]?.[trimmed];if(ex)return str.replace(trimmed,ex);let out=trimmed;const dict=words[lang]||{};Object.entries(dict).sort((a,b)=>b[0].length-a[0].length).forEach(([a,b])=>{out=out.replace(new RegExp(`\\b${a}\\b`,'gi'),b)});return str.replace(trimmed,out)}
function apply(root=document.body){if(busy)return;busy=true;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(n.parentElement?.closest('script,style,option[value]'))continue;if(!originals.has(n))originals.set(n,n.nodeValue);n.nodeValue=translate(originals.get(n))}root.querySelectorAll?.('[placeholder],[title],[aria-label],[data-panel-title]').forEach(el=>{let m=attrs.get(el);if(!m){m={};attrs.set(el,m)};['placeholder','title','aria-label','data-panel-title'].forEach(a=>{if(el.hasAttribute(a)){if(!(a in m))m[a]=el.getAttribute(a);el.setAttribute(a,translate(m[a]))}})});document.documentElement.lang=lang;busy=false}
function setLanguage(v){lang=v||'en';try{localStorage.setItem('simplerig-language',lang)}catch{}apply();window.dispatchEvent(new CustomEvent('simplerig-language-changed',{detail:{lang}}))}
select.addEventListener('change',()=>setLanguage(select.value));window.addEventListener('simplerig-language-refresh',()=>apply());new MutationObserver(m=>{if(!busy)requestAnimationFrame(()=>apply())}).observe(document.body,{subtree:true,childList:true,characterData:true});
try{select.value=localStorage.getItem('simplerig-language')||select.value}catch{}setLanguage(select.value);
})();
