(()=>{'use strict';const q=id=>document.getElementById(id),svg=q('rigCanvas'),wrap=svg?.closest('.canvasWrap');if(!svg||!wrap)return;
// Keep legacy calculation nodes in the DOM for compatibility with existing event handlers.
// They are fully hidden by the workspace CSS and are not part of the user interface.
// popovers
function pop(id,title){const p=document.createElement('section');p.className='sr-pop';p.id=id;p.hidden=true;p.innerHTML=`<div class="sr-pop-head"><h3>${title}</h3><button type="button">Close</button></div><div class="host"></div>`;p.querySelector('button').onclick=()=>p.hidden=true;document.body.appendChild(p);return p}function toggle(p){document.querySelectorAll('.sr-pop').forEach(x=>{if(x!==p)x.hidden=true});p.hidden=!p.hidden}
const project=pop('srProject','Project details'),build=pop('srBuild','Build This'),background=pop('srBackground','Background & scale');const prod=document.querySelector('.production-details');if(prod){prod.style.display='grid';project.querySelector('.host').append(prod)}const bd=q('buildThisDock');if(bd){bd.style.display='block';build.querySelector('.host').append(bd)}
const bgTitle=[...document.querySelectorAll('#workspace2d>aside:last-child .title')].find(x=>x.textContent.trim()==='Background');if(bgTitle){const g=bgTitle.nextElementSibling;background.querySelector('.host').append(bgTitle);if(g)background.querySelector('.host').append(g)}background.querySelector('.host').insertAdjacentHTML('beforeend','<hr><p class="bg-calibrate-note">After positioning the background, choose two points with a known distance. The layer can only be locked after scale is applied.</p><button id="bgPick">Choose two points</button> <input id="bgKnown" type="number" value="1" min="0.001" step="0.01" style="width:80px"> <select id="bgUnit"><option>m</option><option>cm</option><option>mm</option></select> <button id="bgApply" disabled>Apply scale</button> <button id="bgLock" disabled>Lock</button><div id="bgState">Upload a background to begin.</div>');
// toolbar
const bar=document.createElement('div');bar.className='sr2-toolbar';const sc=document.createElement('div');sc.className='sr2-scroll';bar.append(sc);const defs=[['selectTool','↖','Select'],['lineTool','╱','Line'],['addRigLineBtn','〰','Rig line'],['arrowTool','➜','Arrow'],['textTool','T','Text'],['measure2dBtn','↔','Measure'],['panTool','✥','Pan'],['duplicateBtn','⧉','Duplicate'],['deleteBtn','⌫','Delete'],['undoBtn','↶','Undo'],['redoBtn','↷','Redo'],['zoomOutBtn','−','Zoom out'],['zoomResetBtn','100','Reset zoom',1],['zoomInBtn','+','Zoom in']];for(const [id,icon,title,wide] of defs){const b=document.createElement('button');b.type='button';b.textContent=icon;b.title=title;if(wide)b.className='wide';b.onclick=()=>{q(id)?.click();sync()};b.dataset.proxy=id;sc.append(b)}function action(t,label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.title=t;b.className='wide';b.onclick=fn;sc.append(b)}action('Build This','BUILD',()=>toggle(build));action('Project','PROJECT',()=>toggle(project));action('Background and scale','BG',()=>toggle(background));action('Edit / Live rope','LIVE',()=>q('liveRopeToggle')?.click());action('Export image','IMAGE',()=>q('downloadImageBtn')?.click());action('Export PDF','PDF',()=>q('downloadPdfBtn')?.click());const lab=document.createElement('label');lab.innerHTML='<input id="srLiveMeasure" type="checkbox" checked> Live length';sc.append(lab);wrap.append(bar);sc.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){sc.scrollLeft+=e.deltaY;e.preventDefault()}},{passive:false});function sync(){bar.querySelectorAll('[data-proxy]').forEach(b=>b.classList.toggle('active',q(b.dataset.proxy)?.classList.contains('active')))}document.addEventListener('click',()=>requestAnimationFrame(sync),true);sync();
// live line readout
const read=document.createElement('div');read.className='sr-live-read';read.hidden=true;wrap.append(read);let dragging=false;svg.addEventListener('pointerdown',e=>{dragging=e.target?.classList?.contains('rig-handle')},true);svg.addEventListener('pointermove',e=>{if(!dragging||!q('srLiveMeasure').checked){read.hidden=true;return}const g=e.target.closest?.('[data-rig="true"]')||[...q('rigLineLayer').querySelectorAll('[data-rig="true"]')].at(-1);if(!g)return;let pts=[];try{pts=JSON.parse(g.dataset.points||'[]')}catch{}if(pts.length<2)return;let d=0;for(let i=1;i<pts.length;i++)d+=Math.hypot(pts[i].x-pts[i-1].x,pts[i].y-pts[i-1].y);const m=d*(Number(q('metresPerCanvasUnit')?.value)||.02),u=q('metricUnit')?.value||'m',v=u==='mm'?m*1000:u==='cm'?m*100:m;read.textContent=`${v.toFixed(u==='m'?2:1)} ${u}`;const r=wrap.getBoundingClientRect();read.style.left=Math.min(r.width-90,e.clientX-r.left+12)+'px';read.style.top=Math.min(r.height-30,e.clientY-r.top+12)+'px';read.hidden=false},true);window.addEventListener('pointerup',()=>{dragging=false;read.hidden=true},true);
// force 2D white without recursive observer
let busy=false;function white(){if(busy)return;busy=true;q('rigLineLayer')?.querySelectorAll('[data-visible="true"]').forEach(n=>{if(n.getAttribute('stroke')!=='#ffffff')n.setAttribute('stroke','#ffffff')});busy=false}const rl=q('rigLineLayer');if(rl)new MutationObserver(()=>requestAnimationFrame(white)).observe(rl,{childList:true,subtree:true});white();
// background calibration
let picking=false,pts=[];const NS='http://www.w3.org/2000/svg';function point(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse())}q('bgPick').onclick=()=>{if(!q('backgroundImage')){q('bgState').textContent='Upload a background first.';return}picking=true;pts=[];background.hidden=true;q('bgState').textContent='Click two points.'};svg.addEventListener('click',e=>{if(!picking)return;e.preventDefault();e.stopImmediatePropagation();pts.push(point(e));if(pts.length===2){picking=false;q('bgApply').disabled=false;toggle(background);q('bgState').textContent='Enter the known distance, then apply scale.'}},true);q('bgApply').onclick=()=>{if(pts.length!==2)return;let v=Number(q('bgKnown').value),u=q('bgUnit').value;if(u==='cm')v/=100;if(u==='mm')v/=1000;const d=Math.hypot(pts[1].x-pts[0].x,pts[1].y-pts[0].y);q('metresPerCanvasUnit').value=(v/d).toFixed(6);q('metresPerCanvasUnit').dispatchEvent(new Event('change',{bubbles:true}));q('bgLock').disabled=false;q('bgState').textContent='Scale applied. Lock the background.'};q('bgLock').onclick=()=>{q('backgroundImage')?.setAttribute('pointer-events','none');q('bgLock').disabled=true;q('bgPick').disabled=true;q('bgState').innerHTML='<span class="bg-lock-ok">Background scaled and locked.</span>'};q('backgroundFile')?.addEventListener('change',()=>setTimeout(()=>{q('bgPick').disabled=false;q('bgLock').disabled=true;q('bgState').textContent='Position the background, then choose two points.'},50));
// ensure 3D canvas resizes after switching
q('switch3d')?.addEventListener('click',()=>{setTimeout(()=>{window.dispatchEvent(new Event('resize'));const host=q('sr3Viewport');if(host&&host.getBoundingClientRect().width<100&&q('sr3StartError'))q('sr3StartError').style.display='flex'},80)});
})();